const swaggerAutogen = require('swagger-autogen')()


const doc = {
    info: {
        version: "1.0.0",
        title: "Etes API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3005",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./src/services/webapp.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./src/server')           // Your project's root file
})